services:
  postgres:
    image: postgres:18
    env_file:
      - ./backend/.env
    container_name: snug-postgres
    # ports:
    #   - "5432:5432"   # optional (for local psql access)
    volumes:
      - pgdata:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U snug_app -d snug"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    platform: linux/amd64
      
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: snug-backend
    env_file:
      - ./backend/.env
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    platform: linux/amd64

  frontend:
    build: ./frontend
    ports:
      - "5173:80"  # map nginx port 80 -> local 5173
    container_name: snug-frontend

volumes:
  pgdata: